# Generated by Django 6.0.3 on 2026-04-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_auto_20210814_2226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
